- hosts: localhost
  connection: local
  tasks:
    - name: building an image
      create_box:
        path: "./"
        dockerfile: "Dockerfile"
        name: "uhramovich/sample"  
    - name: pushing an image
      push_plugin:
        repository: 'uhramovich/sample' 
